### ISSUE TITLE
Expose memray reporters as part of public API

### ISSUE THREAD

**Issue by corleyma** [bloomberg/memray#122]
### Is your feature request related to a problem? Please describe.
Using the memray API, via the `memray.Tracker` class, makes it simple to collect the raw results of profiling.  However, the excellent reporters that render that data are not importable from `memray.reporters`, making it difficult to e.g. generate flamegraphs as part of an automated process.

The current workaround would be to use subprocess to call out to memray reporting commands, but that's needlessly heavy.

### Describe the solution you'd like
The [Pyinstrument API ](https://github.com/joerick/pyinstrument) is not entirely dissimilar from the memray API, and I think it provides some [good examples](https://pyinstrument.readthedocs.io/en/latest/reference.html#pyinstrument.Profiler.output) for how API access to renderers might work.

E.g., it would be nifty if the `Tracker` instance exposed a `.report(reporter: MemrayReporter = TreeReporter) -> str` that renders the results of profiling as HTML or text.  This might require bigger changes to the Tracker API, since I believe profiling results are not kept available in memory.

### Describe alternatives you've considered
A reasonable alternative would be to expose file-based reporter classes that look mostly similar to today's reporter classes.  Ideally, this would involve adding a common abstraction to all of the reporter classes to handle common functionality like reading memray results into memory from file, such that each reporter class could take a string filepath or Pathlib path object for the input data, and return rendered output.  This could have the benefit of drying out some of the repeated logic in the various reporter commands.

**Comment by godlygeek** [comment]
As of right now, we're not planning to provide an API for the reporters. For working at the high level, you can already use `subprocess` to call out to the reporters, as you noted. We're not currently willing to provide an API for working with reporters at any lower level than that right now, because things are still changing pretty rapidly in Memray, and we aren't ready to support backwards compatibility on any of the APIs involved in reading from a capture file yet.
