### ISSUE TITLE
Support for Pypy

### ISSUE THREAD

**Issue by elkd** [bloomberg/memray#140]
Thanks for releasing Memray, I like the elegance of it's api. I'm curious if it'll be possible to use Memray with Pypy? Currently, I can't build from source in a Pypy 3.8 virtual env. I have ibunwind-dev and liblz4-dev installed, and I can build from the source inside CPython venv.

Is adding support for Pypy a stretch or there's something I can do to successfully build in Pypy?

**Comment by pablogsal** [comment]
Hi @elkd and thanks for opening an issue.

We have not investigated PyPy support, and we don't know how much work would it be to add PyPy support or even if is possible. We use a bunch of CPython C-APIs that I am not sure are supported by PyPy and we use Cython, which generates code that binds directly to CPython implementation details so I am not sure if there are translation layers available.

For this reason, unfortunately, there is not very likely that we will dedicate a lot of work in the near tear towards this :(

**Comment by godlygeek** [comment]
I played with this for a few minutes, and found several things that won't work. Among the most concerning:
no `PyEval_SetProfile`, and no `PyFrame_GetLineNumber`. Plus no ability to override the pymalloc allocators, but we could always just disable those when running on PyPy.

Less broken stuff than I expected to find, honestly. We could work around not having `PyEval_SetProfile` by calling `sys.setprofile` perhaps, but I'm not sure how to work around the lack of `PyFrame_GetLineNumber`.

**Comment by godlygeek** [comment]
It might be possible to (mostly) support PyPy one day, but it doesn't even make sense for us to attempt it until development slows down a lot. Because PyPy does not support the full CPython C API, adding support for PyPy isn't without both costs and risks. Working around the missing features and coming up with solutions that are compatible with both PyPy and CPython would cost us extra development effort, and once we did have support for PyPy, it would constrain the features and architecture that we're able to have going forward to only what can reasonably be implemented in both PyPy and CPython.

PyPy might eventually be worth supporting, but there's too much risk to doing it now.
