### ISSUE TITLE
Using more cpu cores to processing .bin files

### ISSUE THREAD

**Issue by scse-l** [bloomberg/memray#158]
## Feature Request

**Is your feature request related to a problem? Please describe.** 
I have several 5GB .bin files, when I run 'memray tree 5GB-bin-file', it takes ten more minutes to get results and memray uses 100% cpu. So is there a method to process one .bin file parallel using more cpu cores ?

**Describe the solution you'd like** 
Use more cpu cores to process .bin files.

**Comment by godlygeek** [comment]
> So is there a method to process one .bin file parallel using more cpu cores ?

Unfortunately, no, all of the processing that needs to be done is very serial. Because of the way the capture file is encoded, skipping around in it isn't really an option, so dividing the work across multiple cores isn't really a possibility.

Can you describe more about your use case? How long are you monitoring your script for to get 5 GB output files? Do you usually look at each output file only once, or do you run multiple reporters on the same output file? Are you capturing native allocations or tracing the Python allocators? Are you using the Memray API, or the `memray run` command?

**Comment by godlygeek** [comment]
The format of the capture files is designed to be fast to write, because we don't want to slow down the user's code more than necessary while we're profiling it. The file isn't particularly fast to read, though, because it requires the reader to serially process the file, reconstructing large amounts of state from incremental delta updates.

One thing that we could consider doing is having another file format that is designed to be efficient to read, and providing some way to transform the current easy-to-write format to the new easy-to-read format. In order to generate the easy-to-read file from the easy-to-write file, though, we'd still need to parse the easy-to-write file once, so this idea would only be faster if you are generating more than one report from the captured data.

**Comment by scse-l** [comment]
> Can you describe more about your use case? How long are you monitoring your script for to get 5 GB output files?
I've monitoring a deep learning program for several days. From the report generated by `memray tree`, there is 70+ million allocations (Number of allocations: 733239093) .
> Do you usually look at each output file only once, or do you run multiple reporters on the same output file? 
Run multiple reporters on the same output file.
> Are you capturing native allocations or tracing the Python allocators? 
I guess i'm capturing native allocations. (With memray.Tracker("outputfile.bin", natice_traces=True)
> Are you using the Memray API, or the `memray run` command?
Use Memray API.

**Comment by scse-l** [comment]
> The format of the capture files is designed to be fast to write, because we don't want to slow down the user's code more than necessary while we're profiling it. The file isn't particularly fast to read, though, because it requires the reader to serially process the file, reconstructing large amounts of state from incremental delta updates.
> 
> One thing that we could consider doing is having another file format that is designed to be efficient to read, and providing some way to transform the current easy-to-write format to the new easy-to-read format. In order to generate the easy-to-read file from the easy-to-write file, though, we'd still need to parse the easy-to-write file once, so this idea would only be faster if you are generating more than one report from the captured data.

Got it, thanks a lot !
