### ISSUE TITLE
Allow installation on OSX/Windows for creation of flamegraphs

### ISSUE THREAD

**Issue by KimiNewt** [bloomberg/memray#168]
## Feature Request

Currently the package installation fails on OSX. However some parts of the package should still be usable (basically everything other than the tracker themselves). 

I've had cases where the actual tracking occurred in a docker container/VM but we later want to view them in various ways on OSX, and that's not possible right now. Furthermore the setup of memray actively fails so it's hard to create projects that rely on it but are multiplatform without having to modify the setup.py significantly.

I suggest that the various tracking functions raise `NotImplementedError` or similar compatibility error but that general installation will still be allowed on non-Linux machines.

**Comment by pablogsal** [comment]
Hi @KimiNewt and thanks for opening the issue.

Unfortunately, is not as easy as you describe because most reporters use compiled components that are only available on Linux to report native frames. 

Is true that for non-native reporting these are not really needed but untangling this and making the compilation conditional to Linux is a bit messy, so unfortunately we are going to reject this feature request.

> I've had cases where the actual tracking occurred in a docker container/VM but we later want to view them in various ways on OSX, and that's not possible right now.

I develop on an OSX machine and the way I do this is that I mount the container VM filesystem (`-v $pwd:/src ` on docker for example) and I run the reporters in the VM and analyze the output outside it (for HTML reporters) for example.

> Furthermore the setup of memray actively fails so it's hard to create projects that rely on it but are multiplatform without having to modify the setup.py significantly.

You can mark the installation conditional to the OS. For example, in a `requirements.txt` you can do:

```
memray; sys_platform == 'linux'

```

**Comment by pablogsal** [comment]
Update! We've now added macOS support to Memray, both for M1 and Intel Macs. It will be included in the Memray 1.3 release, which we are releasing today.
