### ISSUE TITLE
stats with --json output

### ISSUE THREAD

**Issue by kapilt** [bloomberg/memray#187]
i'm trying to measure the effect of a code change / branch to some application code. the app code uses multiprocessing pools to perform work. using memray with --follow-fork generates per pid files with parentage, but getting that to aggregate requires a custom script. unfortunately memray only does pretty output instead of json output afaics, so the aggregated stat view here can't easily be scripted  or parsed because its all terminal escape codes and formatted text. 

so the request would be to have a --json parameter  or --format=json parameter on some of the reporting commands (stats would be relevant for this use case).

**Comment by godlygeek** [comment]
We wouldn't be willing to support this for all reporters, but if we scope it to only the `stats` reporter in particular, this seems like a reasonable request. It looks like the changes required to support that would be pretty localized, to only https://github.com/bloomberg/memray/blob/253b15bdfbd26ccff1779b1b5401cc09f78fb58d/src/memray/reporters/stats.py#L92 and the functions it calls. Plus some changes in https://github.com/bloomberg/memray/blob/253b15bdfbd26ccff1779b1b5401cc09f78fb58d/src/memray/commands/stats.py#L13 to accept the new `--json` argument and https://github.com/bloomberg/memray/blob/253b15bdfbd26ccff1779b1b5401cc09f78fb58d/src/memray/commands/stats.py#L36 to detect that `--json` was used and to pass the flag to `render`.

I've labelled this as "good first issue", since I think it makes a pretty easy place for someone to make a contribution to Memray. If anyone wants to pick this up and work on it, the first step would be deciding on a schema for the JSON this will return - what fields will be included, and what format the values will be in. We'd need to decide if it's more valuable to include the information displayed in the histogram in the JSON, or to include the raw information that's used to compute the histogram, for instance.

**Comment by vmesel** [comment]
Hey guys, came across your repo and I'm willing to help on this issue:

What do you think about this JSON output?

```
{
    'stats': {
        'total_num_allocations': 0000,
        'total_memory_allocated': '128M',
        'allocator_types': [
            "type_1",
            "type_2",
        ],
        'top_allocations_by_size': [
            {
                "location": "xpto.py",
                "size": 13
            },
            {
                "location": "xpto.py",
                "size": 28
            },
            {
                "location": "xpto.py",
                "size": 120
            },
        ],
        'top_allocations_by_count': [
            {
                "location": "xpto.py",
                "count": 120
            },
        ],
    }
}
```

**Comment by godlygeek** [comment]
Hm. `total_memory_allocated` should be an integer, not a string - and the units should be clear, I'd call it `total_bytes_allocated` instead.

I think `allocator_types` ought to instead be something like:
```py
    'allocation_count_by_allocator': {
        'MALLOC': 10,
        'REALLOC': 20,
        'MMAP': 30,
    }
```
or something like that.

Making `top_locations_by_size` and `top_locations_by_count` a list of objects seems reasonable to me. We could also consider including any of the information in https://github.com/bloomberg/memray/blob/ed876621846e21e22df2ffa203058b3850065787/src/memray/_metadata.py#L5-L15

Much of that doesn't make sense in textual output, but could be handy in the JSON - start/end time, peak memory, command line, pid, and Python allocator all seem like they would make sense to include in the JSON output. Perhaps the has_native_traces flag, too. Total allocations is already being included, and total frames doesn't make sense to include (I've been thinking about removing that entirely...)

**Comment by vmesel** [comment]
Awesome, I'm going to make a preview of the code so I share it with you guys over here.

**Comment by pn320** [comment]
Is this something that needs to be worked on, or is it just a case of a pull request waiting to be merged?

**Comment by pablogsal** [comment]
> Is this something that needs to be worked on (if so, I'd like to!), or is it just a case of a pull request waiting to be merged?

Someone needs to do a PR with the change still.

**Comment by pn320** [comment]
Perfect, I'll work on it, hopefully get the PR up by next week.

**Comment by meersuri** [comment]
Hi, If someone else isn't already working on this, I'd like to give it a try

**Comment by kapilt** [comment]
thanks @oddsun and @godlygeek, looking forward to trying this out in the next release.
