### ISSUE TITLE
Allow disabling experimental support warning via env-var

### ISSUE THREAD

**Issue by gaborbernat** [bloomberg/memray#194]
For example, https://github.com/bloomberg/memray/blob/ed876621846e21e22df2ffa203058b3850065787/src/memray/_memray.pyx#L325. Printing out error on the stderr makes test that checks the stderr break even if memray works correctly.

Also ideally we should only print it once, but now it prints it for all instance creation (in case of pytest-memray) this is the number of tests we have (perhaps guard it with some kind of global variable?).

**Comment by gaborbernat** [comment]
@godlygeek @pablogsal can we do this? (this makes today pytest-memray very noisy on macos...)

**Comment by godlygeek** [comment]
> Printing out error on the stderr makes test that checks the stderr break even if memray works correctly.

Hm. That's quite unfortunate - in an ideal world, `pytest-memray` wouldn't be able to change the outcome of tests...

It seems reasonable to me to provide some way to prevent Memray from printing these messages when run by `pytest-memray`, though ideally we'd shift things so that `pytest-memray` prints them itself, once per run - so that the user still sees the warning that things might not work right and how to report it, but it couldn't affect the outcome of any tests, and doesn't get spammed to the terminal/logs.

**Comment by gaborbernat** [comment]
So what's the path ahead, should memray allow disabling this we could stil print it at the end of test runs, but for that we need to be able to disable it...
