### ISSUE TITLE
Report memory bandwidth

### ISSUE THREAD

**Issue by ma-sadeghi** [bloomberg/memray#221]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

One thing that needs to be checked before trying to parallelize a code is to see whether or not memory bandwidth has already been saturated. Adding this feature would help programmers make more informed decisions as to when parallelizing a code is worth the effort.

### Describe the solution you'd like

I'd like to see a memory bandwidth (MB/s) metric as part of the profile.

### Alternatives you considered

Currently, I use [pcm](https://github.com/opcm/pcm) to track memory bandwidth, but it's very manual and tedious (as I need to dynamically monitor the terminal output generated by pcm by "eye" while the program is running and somehow draw conclusions!)

**Comment by pablogsal** [comment]
Hi @ma-sadeghi and thanks for opening this issue.

 What you are asking seems to be related to measuring memory bandwidth (at least in the same sense as `pcm` does). `pcm` can do those measurements because they have much more control over the CPU, instructions and many other things that we don't (is an INTEL product and only works with INTEL processors). On the other hand, `memray` is a general-purpose heap memory profiler, which is a very different tool. `memray` can only track APIs that increase the heap size like `malloc`, `realloc`, `mmap`... but it can not track memory bandwidth and other CPU/RAM specific metrics as we don't have visibility on those. `memray` can be used to track memory usage (as in, how much memory is being used by a program and where that memory came from) but any other metric regarding memory would require another specialized tool that has more control over the hardware and the drivers.


Unfortunately, I am afraid that you will need to find some other tool that can do these reports. In any case, thanks for opening the issue with us and thanks for using memray ❤️

**Comment by ma-sadeghi** [comment]
Hi @pablogsal, thank you so much for your detailed response, it all makes sense :)
