### ISSUE TITLE
Add manpages for the memray cli

### ISSUE THREAD

**Issue by inglor** [bloomberg/memray#28]
## Feature Request

**Is your feature request related to a problem? Please describe.**
N/A.

**Describe the solution you'd like**
Provide manpages for the `memray` tool

**Describe alternatives you've considered**
Could be as simple for start as the help page

**Teachability, Documentation, Adoption, Migration Strategy**
Users would RTFM :)

**Comment by godlygeek** [comment]
Hm. Where would we put them in order for `man` to pick them up? I imagine that this tool will generally be installed into a virtualenv, or possibly a user's home directory in `~/.local` - in either of those cases, I don't think `man`'s default configuration on any distro would find them.

Unless your goal is for us to provide man pages that a packager could pick up for installation into the system's /usr/share/man directory... Can you explain how you imagine the man pages being used?

**Comment by inglor** [comment]
Exactly as you described for the systems `/usr/share/man` as I'm package maintainer for Arch Linux [1] :)

[1]: https://archlinux.org/packages/community/x86_64/memray/

**Comment by godlygeek** [comment]
OK, that seems reasonable. Sphinx supports man page output, so in theory this wouldn't be too tough to do (though the devil is in the details when it comes to Sphinx). 

Can you point to any existing Python CLI tools that are producing man pages that an Arch package can easily pick up? I'm wondering where we'd need to put them, and things like that - it would be nice if there's a package we can mimic.

**Comment by inglor** [comment]
Maybe this? https://github.com/nicolargo/glances

It's not the responsibility of the application to install it somewhere specific (as different distros might have different patterns) but as long as there's man page the package tool (`pacman` in Arch Linux) can put it in place.

PS: package tools usually handle compression to `.gz`

**Comment by pradyunsg** [comment]
So... pip has man pages, however it maintains separate sources for man vs HTML documentation. I ended up with that approach since these two documentation sets realistically need to contain different drastically information (man is typically more of a reference-only content while the HTML docs use all the nice things you can do in HTML, like having navigation and interactivity + contain tutorials, explanations and development documentation as well).

https://github.com/pypa/pip/tree/main/docs

We could do something like that. That said, I'm very curious to learn how other CLI tools with Sphinx documentation provide man pages. :)

**Comment by godlygeek** [comment]
I played around a little bit with Sphinx's man page generation today. I think @pradyunsg is correct - we won't get nice looking results out of the same sources as the HTML docs are generated from, since they make assumptions about how they'll be presented - most notably including images for all the examples, which Sphinx's man page writer helpfully just replaces with the literal text `[image]`. We could generate some _extremely_ bare bones man pages automatically using `sphinx-argparse`, but even that would just match the output of `memray <cmd> --help`, and it would require us keeping a separate source tree of manual page sources, and remembering to keep them up to date as new subcommands are added. Moreover, we'd need to somehow include them in our sdists, which means either checking in the generated groff code or somehow generating it at the point the sdist is created (and therefore before the package has been built and installed and before it can be imported). Neither of those options are very appealing...

I'm inclined to think this is too much work for the benefit it would give.

**Comment by pablogsal** [comment]
I concur so I am closing this as won't fix it. Thanks for the suggestion @inglor!

**Comment by inglor** [comment]
Thanks for considering it and time spend investigating.
