### ISSUE TITLE
Make memray reproducible

### ISSUE THREAD

**Issue by inglor** [bloomberg/memray#30]
## Bug Report

**Current Behavior**
memray as it stands is not reproducible [1]

**Input Code**

The below are the reproducible tests Arch Linux infrastructure automatically perform on each package (periodically). As you see from the diffscope the Build-ID is different on the .so package.

https://reproducible.archlinux.org/api/v0/builds/267424/diffoscope
https://reproducible.archlinux.org/api/v0/builds/267424/log

**Expected behavior/code** 
Expected behavior for this is for memray to be reproducible (byte-for-byte) 

**Environment**

Package is build according to PKGBUILD from Arch Linux repos [2]

**Possible Solution**

Not entirely sure but I think this is because it's build from within cython and doesn't read the Build_Date or something

**Additional context/Screenshots**

https://reproducible-builds.org/docs/source-date-epoch/

[1]: https://reproducible-builds.org
[2]: https://archlinux.org/packages/community/x86_64/memray/

**Comment by pablogsal** [comment]
I have investigated and seems that the reason the build ids are different is due to some Cython symbols being migrated when pip does an isolated build as the path is different. Everything else seems the same:
![Screenshot 2022-04-21 at 12 15 13](https://user-images.githubusercontent.com/11718525/164448210-ba835534-9a2d-4f1a-ab0b-70c7334a224c.png)
![Screenshot 2022-04-21 at 12 15 25](https://user-images.githubusercontent.com/11718525/164448219-5ec92d8f-8a6d-4f28-94fb-f9b446cedfab.png)
![Screenshot 2022-04-21 at 12 15 33](https://user-images.githubusercontent.com/11718525/164448226-db2ba8f1-87a6-436b-816b-b46df335b1c7.png)

**Comment by inglor** [comment]
Hmm seems like this is a bug for `cython` then instead of `memray`. Should I raise an issue somewhere else and link it here?

**Comment by pablogsal** [comment]
> Hmm seems like this is a bug for `cython` then instead of `memray`. Should I raise an issue somewhere else and link it here?

I am not sure is a bug in Cython. The problem is that when `gcc` builds DWARF it burns the source location and the source location is different with `pip` isolated installation because it uses a different temporary directory. This problem should also appear with the vendored patched `libbacktrace` as the build system builds it in a temporary directory but for some reason that's not a problem, it seems (likely because it doesn't include DWARF by default).

**Comment by inglor** [comment]
I tried with `options=('!strip')` on the PKGBUILD but no luck either :/

**Comment by inglor** [comment]
After a bit of chatting in IRC [1] @diabonas came up with the solution [2] and 1.0.3-3 should be reproducible (it might take some time to appear on the UI)

[1]: #archlinux-reproducible
[2]: https://github.com/archlinux/svntogit-community/commit/027e4bcf7f6c3a28bbbd1ecd16f2e436fbf2391f

**Comment by pablogsal** [comment]
Ah, good point, let's reopen this issue to consider fixing that!
