### ISSUE TITLE
memray api

### ISSUE THREAD

**Issue by Okroshiashvili** [bloomberg/memray#327]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

The documentation is not as great as the package itself, especially for newcomers. I've gone thru it few times to figure out things. For example my main interest is **memray api usage** You're lucking examples of how to use it in different way. For example how to create decorator with memray to profile a particular function/method.

### Describe the solution you'd like

Adding more examples for **memray api** would be really helpful.

**Comment by godlygeek** [comment]
> For example how to create decorator with memray to profile a particular function/method.

I don't think that's a pattern that we should encourage. Memray tracking is inherently thread-unsafe: when you start tracking, all allocations made by the entire process get tracked until you disable tracking. If you wrapped some function up in a wrapper that always tries to start Memray tracking every time it's called and stop tracking after it returns, it would no longer be possible to call that function in two different threads. You wouldn't even be able to call one decorated function from another - the inner one would fail to set up tracking because the outer one already did it, and would raise an exception saying so.

**Comment by Okroshiashvili** [comment]
Hi @godlygeek 

Thanks for clarifying things. 🙏  Now, I see why decorating is not good idea and I will not enforce it anymore.

However, adding some examples in docs will help newcomers like me ☺️
