### ISSUE TITLE
empty flamegraph/summary with large memray dump

### ISSUE THREAD

**Issue by masterkidan** [bloomberg/memray#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello folks, 
I am using the memray api to automatically capture some traces around celery tasks. The idea is I start the capture when the before the task is run and stop it after the task is finished. The dump file is fairly large (around 300 MB). After capturing it, when I try to render the flamegraph/table, the flamegraph/table shows up as empty, despite being 40 MB in size.  The same is true for the memray summary command as well.

Interestingly, the memray stats/memray tree commands work as expected though and generate a reasonable output, describing what the largest allocators are etc.. If I were to use memray attach and dump it to a file on the same machine, I am able to get a flamegraph generated. 

### Expected Behavior

flamegraph/table should not be empty

### Steps To Reproduce

It is hard to provide repro steps here. What I can share is that the heap gets as l large as 40 GB.

### Memray Version

1.10.0

### Python Version

3.9

### Operating System

Linux

**Comment by pablogsal** [comment]
Hi @masterkidan 

Please understand that without a reproducer we cannot help you here. Can you at least send us the dump file so we can take a look?

**Comment by pablogsal** [comment]
> . If I were to use memray attach and dump it to a file on the same machine, I am able to get a flamegraph generated.

What do you mean "on the same machine"? Does this mean you are generating in one machine and analysing in another?

**Comment by masterkidan** [comment]
Just wanted to clarify that I was analyzing it on the same machine as where I had generated the report. I am happy to share the dump file privately. Is there some place where I can upload it?

**Comment by masterkidan** [comment]
github doesn't allow me to upload files > 25 MB in size

**Comment by pablogsal** [comment]
> github doesn't allow me to upload files > 25 MB in size

You can upload it elsewhere and paste a link here

**Comment by pablogsal** [comment]
Otherwise you can send it to me at pablogsal [AT] gmail [DOT] com

**Comment by masterkidan** [comment]
K, sent a one drive link to the above email, lmk if you need anything else. Thanks for the help, and for this amazing tool!

**Comment by pablogsal** [comment]
Can you confirm the memray version you used? I am getting

```
Reason: The provided input file is incompatible with this version of memray.: unspecified iostream_category error
```

When I use memray 1.10.0

**Comment by masterkidan** [comment]
That's odd. It does say memray 1.10.0 when I run `memray --version`

**Comment by godlygeek** [comment]
It seems like something has replaced every 0x0A byte in that capture file with a 0x0D 0x0A pair, as though `unix2dos` was run on it, or something like that... That's why the version number doesn't match. The capture file is supposed to contain a 4-byte little endian integer with a value of 10 for the capture format version (0x0A000000), and it instead contains a 4-byte little endian integer with a value of 2573 (0x0D0A0000).

All I can imagine is that something treated it as text instead of binary and replaced every LF with CRLF.

**Comment by godlygeek** [comment]
It does seem to parse successfully if I drop every 0x0D that is followed by a 0x0A from it... 👀

**Comment by masterkidan** [comment]
I had to copy from the Linux server to my windows box, maybe that runs it through unix2dos somewhere … though it’s weird.

**Comment by godlygeek** [comment]
Well, here's what I can tell you: the flamegraph you sent (flamegraph4.html) is truncated:

```shell-session
$ tail -c 100 flamegraph4.html
,[1708646587137,12357906432,12096164517],[1708646587147,12357906432,12096164517],[1708646587157,1235
```

That ought to end with a `</html>`. So, that's why that isn't working.

Same problem on the `table_dump.html` that you sent:
```shell-session
$ tail -c 100 table_dump.html
800,12095838352],[1708640199744,12356300800,12095838352],[1708640199754,12356300800,12095838352],[17
```

Both of those are truncated in the middle of writing some JSON data into the HTML document. That's not something Memray did wrong - that's not something we even _could_ do wrong.

Moreover, if I drop every CR that is followed by an LF from the `dump.memtrace` that you sent, then `memray flamegraph` does successfully generate a flame graph HTML which loads successfully for me.

So: my educated guess here is that you exceeded your disk quota on whatever system you were running this on, and so only part of the HTML file contents got written.

Can you check if it might be something like that?

**Comment by drienkop** [comment]
Hi @masterkidan, do you mind sharing an example of using the Tracker with a celery task the way you described in your original post? Thanks!
