### ISSUE TITLE
Dependency on typing_extensions for version of Python earlier than 3.8 no longer makes sense given that Python 3.7 is way past EOL

### ISSUE THREAD

**Issue by tleonhardt** [bloomberg/memray#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The memray [setup.py](https://github.com/bloomberg/memray/blob/main/setup.py#L93) file has an `install_requires` dependency line which looks like so `"typing_extensions; python_version < '3.8.0'",`. 

Python 3.7 hit EOL over a year ago on 2023-06-27 when even security updates ended for it: https://devguide.python.org/versions/

This may seem pedantic, but my company has an exquisitely strict software providence policy and we are only allowed to use open-source dependencies with approved licenses. Unfortunately our automation detects that `memray` requires ` typing_extensions` and finds that that does not have an approved license.  This means I cannot sue `memray` and since `ray[default]` has a dependency on `memray`, in turn I cannot use `ray[default]`.

So I am kindly requesting you remove the one line that no longer makes sense so I can finally use `ray`.  Pretty please ;-)

This request is I suppose equivalent with removing support for Python 3.7

### Expected Behavior

`memray` no longer has a dependency on `typing_extensions` for any supported version of Python since currently only 3.8+ are within [Python EOL](https://devguide.python.org/versions/).

### Steps To Reproduce

Code inpsection by looking at line 93 of [setup.py](https://github.com/bloomberg/memray/blob/main/setup.py#L93)

### Memray Version

Latest

### Python Version

3.7

### Operating System

macOS, Linux

### Anything else?

If it helps, I'm happy to submit a PR, but it is probably a trivial 1-line change to delete a line.

**Comment by godlygeek** [comment]
Memray still supports Python 3.7: https://github.com/bloomberg/memray/blob/5c0b0dfe68b5aabcf3753be320fdd41e9f5df0f3/setup.py#L306

Our general policy is to continue to support even unsupported interpreter versions until the maintenance burden of doing so becomes onerous, exactly because we know that we have enterprise users who have trouble keeping up with the CPython release cadence. If it's not difficult for us to support an EOL version like 3.7, we'd rather continue supporting rather than making it so that anyone who is for some reason stuck with an old interpreter version is also stuck with an old version of Memray.

Setting aside the question of whether or not we ought to support Python 3.7 for the moment...

> This may seem pedantic, but my company has an exquisitely strict software providence policy and we are only allowed to use open-source dependencies with approved licenses. Unfortunately our automation detects that `memray` requires ` typing_extensions` and finds that that does not have an approved license.

But `typing_extensions` uses the same license as the Python interpreter! Compare [typing_extensions's license](https://github.com/python/typing_extensions/blob/main/LICENSE) versus [CPython's license](https://github.com/python/cpython/blob/main/LICENSE) - they differ only in the copyright dates. The most recent commit to the `typing_extensions` LICENSE file has a commit message of "Sync LICENSE with CPython". Surely if you're allowed to use the Python interpreter, you're also allowed to use `typing_extensions`, as both are released under the same license. This seems like a bug in your automation that you're asking us to work around by dropping support for a version of Python that's still fairly heavily used, albeit out of security support.

**Comment by tleonhardt** [comment]
I understand your point of view on supporting old Python versions which are past their EOL and are no longer receiving security updates. As such you can probably just close this and I will continue to not be able to use `ray`.

Getting approval to use something like his requires approval from our lawyers on a case-by-case basis which is time consuming and expensive. For something like Python itself it is worth it, for something like typing_extensions, it isn't.
