### ISSUE TITLE
Memray --aggregate optional query

### ISSUE THREAD

**Issue by xty438307820** [bloomberg/memray#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

I try to use memray run --aggregate to reduct the capture file size, but I found that the .bin file always 0 byte no matter how long the process runs. what's happening?
thank you!

### Memray Version

1.14.0

### Python Version

3.11

### Operating System

Linux

**Comment by pablogsal** [comment]
In order for us to help you you need to provide some example code to reproduce the problem you are experiencing or unfortunately we won't be able to do much

**Comment by godlygeek** [comment]
> the .bin file always 0 byte no matter how long the process runs

That's expected behavior. Records are only written to the .bin file once tracking stops - so, either when the process ends, or when `memray detach` is used, or when a `with memray.Tracker():` block completes. See [the documentation](https://bloomberg.github.io/memray/run.html#aggregated-capture-files), which says:

> Also, note that if the process is killed before tracking ends (for instance, by the Linux OOM killer), then the process will die before it finishes calculating its statistics, and so no useful information is ever written to the capture file. With the default file format, the capture file is usually still usable even if the process crashes or is killed, but with the aggregated file format it is not.
